name: mlm
channels:
  - conda-forge
dependencies:
  - ipykernel
  - python=3.10
  - PyGithub
  - pip
  - pip:
    - pystac
    - pystac-client
    - black[jupyter]
    - loguru
    - boto3
    - folium
    - pandas
    - geopandas
    - botocore
    - geojson
    - tqdm