MLFLOW_TRACKING_URI: http://127.0.0.1:5000
stac_reference: "https://raw.githubusercontent.com/eoap/machine-learning-process/main/training/app-package/EUROSAT-Training-Dataset/catalog.json"
BATCH_SIZE: 
    - 2
    - 4
CLASSES: 10
DECAY: 
    - 0.1
    - 0.5
EPOCHS: 
    - 3
    - 5
EPSILON: 
    - 0.000001
    - 0.000005
LEARNING_RATE: 
    - 0.0001
    - 0.0005
    
LOSS: 
    - categorical_crossentropy
    - sparse_categorical_crossentropy  
MEMENTUM: 
    - 0.95
    - 0.79
OPTIMIZER: 
    - Adam
    - sgd
REGULARIZER: 
    - None
    - l1l2
SAMPLES_PER_CLASS: 10
# MLFLOW_TRACKING_URI: http://my-mlflow:5000
