BATCH_SIZE: 2
CLASSES: 10
DECAY: 0.1
EPOCHS: 50
EPSILON: 1.0e-06
LEARNING_RATE: 0.0001
LOSS: categorical_crossentropy
MEMENTUM: 0.95
OPTIMIZER: Adam
REGULARIZER: None
SAMPLES_PER_CLASS: 10
stac_reference: https://raw.githubusercontent.com/eoap/machine-learning-process/main/training/app-package/EUROSAT-Training-Dataset/catalog.json
