input_reference:
  - https://planetarycomputer.microsoft.com/api/stac/v1/collections/sentinel-2-l2a/items/S2B_MSIL2A_20230629T072619_R049_T36KXE_20240906T024049 # Mosambique
  # - https://planetarycomputer.microsoft.com/api/stac/v1/collections/sentinel-2-l2a/items/S2B_MSIL2A_20230626T071619_R006_T39SWV_20240928T052855 # Iran